### ISSUE TITLE
depth_buffer

### ISSUE THREAD

**Issue by mougg-78** [waiyc/Bin-Picking-Dataset-Generation#2]
when use p.getCameraImage I can get depth.img

there is the code in your code:
depth_buffer_opengl = np.reshape(images[3], [CAMERA_IMG_WIDTH_, CAMERA_IMG_HEIGHT_])
depth_opengl = CAMERA_FAR_ * CAMERA_NEAR_ / (CAMERA_FAR_ - (CAMERA_FAR_ - CAMERA_NEAR_) * depth_buffer_opengl)
I want to ask what's the meanning of depth_buffer_opengl, pixel in depth_buffer_gl is the value from the camera to a position?
and  CAMERA_FAR_ * CAMERA_NEAR_ / (CAMERA_FAR_ - (CAMERA_FAR_ - CAMERA_NEAR_) * depth_buffer_opengl) can you explain this formula.
Looking forward to your reply!!!!
Thanks.

**Comment by waiyc** [comment]
Hi sorry for the late reply. You can refer to this link for more info https://stackoverflow.com/questions/59128880/getting-world-coordinates-from-opengl-depth-buffer
