### ISSUE TITLE
Non-square camera resolution results in stretched out depth and segmentation images

### ISSUE THREAD

**Issue by Levaru** [waiyc/Bin-Picking-Dataset-Generation#3]
The resolution of my 3D scanner is 1032x772. I tried to input these values into the script but the resulting depth and segmentation images are stretched out. 
This is a depth image with a 0.5 aspect ratio for example:
![001_depth](https://user-images.githubusercontent.com/46074016/155369416-1ee3a692-2220-4a3e-b03a-7d2deccbe019.png)

I'm not familiar with pybullet, am I using the script wrong? Do I even need to modify the virtual camera to try and simulate my 3D scanner as close as possible or are the standard settings good enough?

**Comment by waiyc** [comment]
Hi sorry for my late reply. Thanks for pointing out the error, I did not notice this issue  for square image. 
I have fixed this issue you may want to git pull for the changes or you can change it manually.

In `1_1_pybullet_create_n_collect.py` , L192 and L194 replace [CAMERA_IMG_WIDTH_, CAMERA_IMG_HEIGHT_] to [CAMERA_IMG_HEIGHT_,CAMERA_IMG_WIDTH_]
