### ISSUE TITLE
How do I correctly simulate a camera with a different kind of parameters?

### ISSUE THREAD

**Issue by Levaru** [waiyc/Bin-Picking-Dataset-Generation#4]
Hi!
I'm trying to simulate my 3D camera as closely as possible to achieve a realistic dataset. But I have absolutely no experience with simulating cameras and pybullet. I have a Photoneo 3D Scanner L with the following parameters:
 
```
Resolution:
  2064x1544
  1032x772 (I use this one)

CalibrationSettings: 
  FocusLength: 7.73036

  PixelSize: 0.00345 x 0.00345

  CameraMatrix: 
    [    f_x,    0.0,    c_x  ]
    [   0.00,    f_y,    c_y  ]
    [   0.00,    0.0,    1.0  ]

    [2240.67,    0.0, 1047.3  ]
    [   0.00, 2240.7,  766.922]
    [   0.00,    0.0,    1.0  ]

  DistortionCoefficients: 
    Format is the following: 
    (k1, k2, p1, p2[, k3[, k4, k5, k6[, s1, s2, s3, s4[, tx, ty]]]])
    (-0.130834, 0.186138, -0.000581972, -0.000368549[, -0.0688114[, 0, 0, 0[, 0, 0, 0, 0[, 0, 0]]]])
```

How would I calculate the view and projection matrix if I only have those parameters but no `FOV`? I did find a calculation for the projection matrix, could you please confirm if it's valid or if there exist a better one?

```
f_x = 2240.67
f_y = 2240.7
c_x = 1047.3 
c_y = 766.922

x_scale = 2 / CAMERA_IMG_WIDTH_ * f_x
y_scale = 2 / CAMERA_IMG_HEIGHT_ * f_y
x_shift = 1 - 2 * c_x / CAMERA_IMG_WIDTH_
y_shift = (2 * c_y - CAMERA_IMG_HEIGHT_) / CAMERA_IMG_HEIGHT_

A = (CAMERA_NEAR_ + CAMERA_FAR_)/(CAMERA_NEAR_ - CAMERA_FAR_)
B = 2 * CAMERA_NEAR_ * CAMERA_FAR_ / (CAMERA_NEAR_ - CAMERA_FAR_)

CAMERA_PROJ_MATRIX_ = [
    [x_scale, 0, x_shift, 0],
    [0, y_scale, y_shift, 0],
    [0, 0, A, B],
    [0, 0, -1, 0],
]
```

Another problem with this camera, is that the camera sensor isn't pointing downwards but is actually offset to the side. You compute the view matrix by using the `CAMERA_TARGET_POSITION_` which is `0,0,0` (center of the bin) but in my setup this isn't the case. How would I compute the view matrix if I only have the XYZ position and rotation matrix of the camera sensor?

I would greatly appreciate your advise on that matter because I'm frankly stuck right now.

**Comment by waiyc** [comment]
Hi,

There is a function [p.computeProjectionMatrix](https://github.com/caelan/pybullet-planning/blob/8953d2dbfd789d5681053eb4993b5ddc0d910a6b/pybullet_tools/utils.py#L1472) which computes projection matrix without the FoV parameter . You can give it a try but I have no experience in using this function. 

For the off-center issue, maybe you want to include the translation offset for the `ensenso_optical_frame` from the center of the camera into the `CAMERA_EYE_POSITION_` and assume that the center of bin is at origin.

**Comment by TheodoroCardoso** [comment]
Hi @Levaru,
Have you made any progress on changing the camera intrinsic in pybullet?
I'm facing a similar challenge and would appreciate any hints.

**Comment by Levaru** [comment]
@TheodoroCardoso 
Not really, but I noticed that it doesn't play a huge role if you only use the point cloud data. If your camera has a fish eye lense or is very far away then it's a different case but for most cameras the standard params should suffice.

The more important parameters are the resolution, distance and FOV. 

I might be completely wrong about that but that's what I noticed in our case.

**Comment by waiyc** [comment]
I will close the issue for now due to no additional activity occurs after 14 days
