### ISSUE TITLE
Visibility of each object

### ISSUE THREAD

**Issue by BharathRajM** [waiyc/Bin-Picking-Dataset-Generation#5]
Firstly, this repo is really brilliant to replicate the synthetic data generation from the Fraunhofer IPA-Dataset. Thanks for open sourcing your implementation.

Is there a way to add the visibility score based on how visible each object is?
Currently the ground truth consists of the 6D pose:x,y,z,quat_x,quat_y,quat_z,quat_w. Can you suggest a way to compute the visibility score for each object w.r.t the camera too?

**Comment by xyjbaal** [comment]
After removing the other invisible points, you can calculate the visible score as  [# of existing points/ # of model points].
It is a very common way in many papers.

**Comment by BharathRajM** [comment]
I appreciate the response,
Can you elaborate it a little bit? I am still figuring out how to do this

**Comment by xyjbaal** [comment]
Follow the third step of this code (3_generate_pcd_fov_points.py#L148), invisible points are removed.
So, the visible score = the number of visible points remaining per part / original number of points of each part.
