### ISSUE TITLE
Getting ground truth poses in the camera frame

### ISSUE THREAD

**Issue by BharathRajM** [waiyc/Bin-Picking-Dataset-Generation#7]
Hey @waiyc !

I am using your repo to recreate the synthetic data to train PPRNET (https://github.com/lvwj19/PPR-Net-plus). 
I saw that the ground truth obtained from the synthetic dataset is w.r.t to the world frame and I was hoping you could help me convert it to the camera frame as done in the Fraunhofer IPA dataset.

Any pointers are really helpful!

**Comment by waiyc** [comment]
Hi @BharathRajM ,

Sorry for my late reply. 
You need to use the camera's TF information worldTcam to compute object pose wrt to camera.
camTobj = camTworld * worldTobj
