### ISSUE TITLE
How to generate test data? 

### ISSUE THREAD

**Issue by lyl1140292193** [waiyc/Bin-Picking-Dataset-Generation#8]
Hello, thank you for your excellent work! But I am confused about following questions.

I generated training data (h5 data) through your code. After I run "python 2_open3d_reconstruct_pcd_scene.py" , txt files were generated in 'scene' folder. There are five columns in one txt file, I don't know what the specific meaning for the fourth and the fifth columns. So does the same with 'pointcloud' folder whose files also have 5 columns.

After I training 'fpcc_train.py' with the above dataset, how can I generate test data in pybullet way? And I also want to check it in real world, how can I transform the traditional pcd files into test files?

Sorry to bother you. Thanks!

**Comment by xyjbaal** [comment]
HI,

The fourth column is the instance label of point.
The 5th column is the center score.

> After I training 'fpcc_train.py' with the above dataset, how can I generate test data in pybullet way? 
   
     I don't quite understand this question. You can generate test data just as you generate training data.

> And I also want to check it in real world, how can I transform the traditional pcd files into test files?

     you can use this code to change pcd to numpy,

    points = o3d.io.read_point_cloud(f, format='auto')
    points = np.asarray(points.points) # change the o3d style data to numpy.

**Comment by lyl1140292193** [comment]
Thanks a lot! Sorry,I misunderstood the format of the data. And I connect the model with scenarios in real-world data! Have a nice day!
