### ISSUE TITLE
How to process my data？

### ISSUE THREAD

**Issue by blandness1217** [waiyc/Bin-Picking-Dataset-Generation#9]
I'm sorry for the interruption, but I would like to know if it is theoretically possible to convert my own collected real-world data into a format that can be trained by FPCC?
<img width="419" alt="原始" src="https://github.com/waiyc/Bin-Picking-Dataset-Generation/assets/96906780/c0710048-ff53-4469-8f60-190c0d2040bd">
<img width="419" alt="点云" src="https://github.com/waiyc/Bin-Picking-Dataset-Generation/assets/96906780/6740a7eb-a563-4c3c-8219-49e685a45a3f">
<img width="295" alt="分割+实例标注" src="https://github.com/waiyc/Bin-Picking-Dataset-Generation/assets/96906780/d438c33e-67e5-478d-9a04-f4e8333c256e">

**Comment by waiyc** [comment]
Yes you can . You can omit the data generation scripts and reformat your data into H5 format 
The data format is in the last python script with the following function name 
>fpcc_save_h5(h5_filename, data)

**Comment by waiyc** [comment]
I will close the issue for now due to no additional activity occurs after 14 days

**Comment by blandness1217** [comment]
Thank you very much for your enthusiastic and detailed reply!
I originally planned to share it with you after I solve this problem, but I have been delayed in trying it recently because I am busy with other things. I will try the suggestions you gave recently and share the results of my attempts with you in time.

**Comment by blandness1217** [comment]
These days I tried to make my own dataset and use fpcc to train, and finally got satisfactory results. I sincerely thank you for your help and wish you well.
